version: "3"
services:
   api:
    image: dalongrong/mysql_demo:v1.0
    ports:
    - "9090:9090"
   mysql:
    build: ./
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EMPLOYEE_RECORDS
      MYSQL_USER: gogs
      MYSQL_PASSWORD: dalongrong
      TZ: Asia/Shanghai
